# Generated by Django 6.0.2 on 2026-02-04 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteMonthSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athelete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboard.athlete')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboard.month')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pace', models.DecimalField(decimal_places=2, max_digits=6)),
                ('athlete_month_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboard.athletemonthsummary')),
            ],
        ),
    ]
