# Generated by Django 6.0.2 on 2026-02-04 01:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_athletemonthsummary_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['date'], 'verbose_name_plural': 'activities'},
        ),
        migrations.AlterModelOptions(
            name='athletemonthsummary',
            options={'ordering': ['month__date']},
        ),
        migrations.AddField(
            model_name='activity',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='athlete_month_summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='leaderboard.athletemonthsummary'),
        ),
    ]
