# Generated by Django 6.0.2 on 2026-02-04 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0003_alter_activity_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athletemonthsummary',
            old_name='athelete',
            new_name='athlete',
        ),
    ]
