# Generated by Django 6.0.2 on 2026-02-04 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0004_rename_athelete_athletemonthsummary_athlete'),
    ]

    operations = [
        migrations.CreateModel(
            name='StravaToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=80)),
                ('client_secret', models.CharField(max_length=80)),
                ('access_token', models.CharField(max_length=255)),
                ('refresh_token', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='strava_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='athlete',
            name='strava_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
