# Generated by Django 6.0.2 on 2026-02-04 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0005_stravatoken_activity_strava_id_athlete_strava_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stravatoken',
            name='access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stravatoken',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
