# Generated by Django 6.0.2 on 2026-02-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0006_alter_stravatoken_access_token_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StravaToken',
        ),
        migrations.AddField(
            model_name='athlete',
            name='strava_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='strava_refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
