# Generated by Django 6.0.2 on 2026-02-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0007_delete_stravatoken_athlete_strava_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='strava_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
