# Generated by Django 6.0.2 on 2026-02-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0008_alter_athlete_strava_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='strava_id',
            field=models.IntegerField(),
        ),
    ]
