# Generated by Django 6.0.2 on 2026-02-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0009_alter_activity_strava_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='strava_id',
            field=models.BigIntegerField(),
        ),
    ]
