# Generated by Django 6.0.2 on 2026-02-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0010_alter_activity_strava_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='icon_colour',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
