# Generated by Django 6.0.2 on 2026-02-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0011_athlete_icon_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.CharField(default='Run', max_length=40),
            preserve_default=False,
        ),
    ]
