# Generated by Django 6.0.2 on 2026-02-05 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0012_activity_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-date'], 'verbose_name_plural': 'activities'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='pace',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
    ]
