# Generated by Django 6.0.2 on 2026-02-16 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0013_alter_activity_options_alter_activity_pace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='icon_colour',
        ),
    ]
