# Generated by Django 6.0.2 on 2026-02-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0014_remove_athlete_icon_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='invalid',
            field=models.BooleanField(default=False, help_text="Used to manually invalidate an activity if it's deemed to be outside the spirit of the game"),
        ),
    ]
