# Generated by Django 6.0.2 on 2026-04-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0015_activity_invalid'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='is_double_points',
            field=models.BooleanField(default=False),
        ),
    ]
