# Generated by Django 6.0.2 on 2026-04-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0016_athlete_is_double_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='is_double_points_month',
            field=models.BooleanField(default=False),
        ),
    ]
