# Generated by Django 6.0.2 on 2026-04-24 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0017_month_is_double_points_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='last_sync_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
