# Generated by Django 6.0.2 on 2026-04-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0018_month_last_sync_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='athletemonthsummary',
            name='current_position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
