# Generated by Django 6.0.2 on 2026-07-01 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0020_deviceregistration_alter_athletemonthsummary_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='strava_connection_status',
            field=models.CharField(choices=[('Connected', 'Connected'), ('Disconnected', 'Disconnected')], default='Connected'),
        ),
    ]
