# Generated by Django 6.0.2 on 2026-07-06 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0022_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
