# Generated by Django 6.0.6 on 2026-07-08 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0024_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='athletemonthsummary',
            name='points',
            field=models.PositiveIntegerField(blank=True, help_text='Points awarded for the final placing once the month has finished', null=True),
        ),
    ]
