# Generated by Django 6.0.6 on 2026-08-03 20:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0025_athletemonthsummary_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
