# Generated by Django 6.0.6 on 2026-08-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0026_log_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Processed', 'Processed'), ('Error', 'Error')], default='New', max_length=20),
        ),
    ]
