# Generated by Django 6.0.6 on 2026-08-03 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0027_log_error_message_log_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Log',
            new_name='WebhookEvent',
        ),
    ]
