# Generated by Django 6.0.6 on 2026-08-10 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0028_rename_log_webhookevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='athletemonthsummary',
            name='disable_double_points',
            field=models.BooleanField(default=False, help_text='Used to manually disable double points for an athlete, mostly for pregnant people'),
        ),
    ]
